---
os:
  - macos-mojave

build_script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - for i in {1..10}; do echo "Run $i"; make test || exit 1; done

on_failure:
  - tar -czf artifact.tgz *
  - appveyor PushArtifact artifact.tgz
